language: objective-c
osx_image: xcode8

xcode_project: OrderedDictionary.xcodeproj
xcode_scheme: OrderedDictionary-iOS
xcode_sdk: iphonesimulator

branches:
 only:
 - master

script:
- xcodebuild clean build test -project OrderedDictionary.xcodeproj -scheme OrderedDictionary-iOS -destination "platform=iOS Simulator,name=iPhone 6s,OS=10.0"
